Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -38,12 +38,10 @@ jobs:
     - name: Build Docker image
       working-directory: peterpet
       run: |
-        DATE=$(date +'%Y%m%d')
         docker build -t ${{ secrets.DOCKER_USERNAME }}/peterpet:peterpet_${{ steps.date.outputs.date }} .
 
     - name: Push Docker image
       run: |
-        DATE=$(date +'%Y%m%d')
         docker push ${{ secrets.DOCKER_USERNAME }}/peterpet:peterpet_${{ steps.date.outputs.date }}
 
     - name: Deploy to Remote Server via SSH
@@ -53,10 +51,18 @@ jobs:
         username: ${{ secrets.SSH_USER }}
         key: ${{ secrets.SSH_KEY }}
         script: |
-          DATE=$(date +'%Y%m%d')
-          docker pull ${{ secrets.DOCKER_USERNAME }}/peterpet:peterpet_${{ steps.date.outputs.date }}
+          # Cleanup old dangling or unused images
+          docker image prune -af || true
+
+          # Remove existing container
           docker stop peterpet || true
           docker rm peterpet || true
+
+          # Remove existing image with same tag if exists
+          docker rmi ${{ secrets.DOCKER_USERNAME }}/peterpet:peterpet_${{ steps.date.outputs.date }} || true
+
+          # Pull and run new container
+          docker pull ${{ secrets.DOCKER_USERNAME }}/peterpet:peterpet_${{ steps.date.outputs.date }}
           docker run -d --name peterpet -p 8080:8080 \
             -e MYSQL_MAIN_JDBC_URL="${{ secrets.MYSQL_MAIN_JDBC_URL }}" \
             -e MYSQL_MAIN_USERNAME="${{ secrets.MYSQL_MAIN_USERNAME }}" \
